# Используем базовый образ с Python3
FROM python:3
# Задаём имя создателя
MAINTAINER Vlasov Aleksandr <vlasov@gmail.com>
#Выбираем временную зону для контенера
ENV TZ = Asia/Yekaterinburg
# Создаем рабочую директорию
WORKDIR /app
# Копируем файлы проекта в рабочую директорию
COPY cesar.py
COPY server.py
# Указываем порт, на котором будет работать приложение
EXPOSE 5555
# Запускаем приложение
CMD ["python3", "server.py"]